2022-05-17 13:05:24,437 ERROR: Exception on /user/max [GET] [in E:\Coding\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Coding\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 81, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Coding\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "E:\Coding\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Coding\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Coding\microblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "E:\Coding\microblog\app\templates\user.html", line 34, in block 'content'
    {% include '_post.html' %}
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2022-05-17 13:05:26,840 ERROR: Exception on /user/max [GET] [in E:\Coding\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Coding\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 81, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Coding\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "E:\Coding\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Coding\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Coding\microblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "E:\Coding\microblog\app\templates\user.html", line 34, in block 'content'
    {% include '_post.html' %}
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2022-05-17 13:05:29,865 ERROR: Exception on /user/max [GET] [in E:\Coding\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Coding\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 81, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Coding\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "E:\Coding\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Coding\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Coding\microblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "E:\Coding\microblog\app\templates\user.html", line 34, in block 'content'
    {% include '_post.html' %}
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2022-05-17 13:05:34,584 ERROR: Exception on /user/max [GET] [in E:\Coding\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Coding\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\Coding\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\Coding\microblog\app\routes.py", line 81, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "E:\Coding\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "E:\Coding\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\Coding\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Coding\microblog\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "E:\Coding\microblog\app\templates\user.html", line 34, in block 'content'
    {% include '_post.html' %}
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "E:\Coding\microblog\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _post.html
2022-05-17 13:25:10,909 INFO: Microblog startup [in E:\Coding\microblog\app\__init__.py:44]
